import EggExperience from '../components/egg/EggExperience';
function Bar({title}:{title:string}) {return <div className="bar"><span className="box" aria-hidden="true"/><span>{title}</span><span className="stripes" aria-hidden="true"/><span aria-hidden="true">↗</span></div>}
export default function Home(){return <EggExperience><main>
<nav><a className="brand" href="#">egg<span>®</span></a><div><a href="#how-it-works">HOW IT WORKS</a><a href="#still-cooking">STILL COOKING</a><a className="nav-cta" href="#early-access">EARLY ACCESS ↗</a></div></nav>
<section className="egg-intro" aria-labelledby="egg-title"><div className="intro-sticky"><div className="egg-caption"><span>ONE EGG.</span><span>A LOT TO KEEP.</span></div><div className="intro-copy"><div className="eyebrow">A SMALL APP FOR EVERYTHING YOU KEEP.</div><h1 id="egg-title">Put all your eggs<br/>in one basket.</h1><p>Screenshots, voice notes, links, photos of doors.<br/>Everything you grab ends up on your Mac.</p><div className="intro-actions"><a href="#how-it-works">SCROLL TO CRACK IT ↓</a><a href="#meadow">SKIP TO THE MEADOW ↗</a></div></div><span className="intro-meta">macOS 14+ · iPhone · Letting people in slowly</span></div></section>
<section className="old-way" id="how-it-works"><div className="dialog window"><Bar title="A QUESTION FROM YOUR COMPUTER"/><div><p>That screenshot is on your other device. Would you like to get up and walk over to it?</p><a href="#everywhere">ABSOLUTELY NOT. ↵</a></div></div><h2>You don’t.<br/>It’s already in the basket.</h2></section>
<section className="everywhere" id="everywhere"><div className="section-label">01 / THE SITUATION</div><h2>You leave eggs<br/>everywhere.</h2><div className="everywhere-grid"><p className="large-copy">On the train.<br/>In a meeting.<br/>At 11pm on your phone,<br/>twice.</p><div><p>Screenshots. Voice notes. Links. A photo of a whiteboard. A photo of a door. Six near-identical shots of one layout because you couldn’t decide.</p><p>Forty-one screenshots from one night you don’t remember taking.</p><p>You drop them and move on. That’s fine. Dropping them is the natural part. Finding them again is the part nobody has solved.</p><div className="receipt"><span>41 eggs today.</span><span>All accounted for. ✓</span></div></div></div></section>
<section className="features" aria-label="How Egg works"><article className="feature window"><Bar title="02 / THE SHORTCUT"/><div className="feature-body"><div><h2>It’s a contact.</h2><p>Your Mac is not a device in a list that may or may not appear.</p><p>It’s a contact. It has a name. It sits in your share sheet with everyone else you know, except it’s a laptop, it’s always there, and it never has other plans.</p><p>Type “e.” Send. It landed while you were reading this.</p></div><div className="type-statement"><span className="keycap">e</span><span className="arrow">→</span><strong>In the<br/>basket.</strong><small>No device picker.<br/>No spinning.<br/>No walking over to check.</small></div></div></article>
<article className="feature window"><Bar title="03 / THE DESTINATION"/><div className="feature-body"><div><h2>One basket.</h2><p>Everything in one feed on your Mac. Newest first. In the order it happened.</p><p>No folders. No inbox to keep at zero. No system for you to design, abandon, and feel bad about in four months.</p><p>Some of it you’ll deal with the moment you sit down. Some will sit there for three weeks.</p><p>Both are correct. That’s what a basket is for.</p></div><div className="big-note">Nothing<br/>to sort.<br/>Nothing<br/>to keep up<br/>with.<span>JUST KEEP IT.</span></div></div></article>
<article className="feature window search-section"><Bar title="04 / THE ONE YOU WERE LOOKING FOR"/><div className="feature-body"><div><h2>It knows<br/>which egg.</h2><p>You won’t remember what you called it. You didn’t call it anything. You were on a train.</p><p>Egg doesn’t need the word. It looks at what’s actually in the picture. Search “wheel” and the screenshot with a wheel in it comes back, having never once been labelled, tagged, filed, or thought about again by anyone.</p><p>Three thousand bookmarks and you can’t find the one. This is that, fixed.</p></div><div className="bookmark-note"><p>You have <strong>3,000</strong> bookmarks.</p><p>You have found <strong>0</strong> of them.</p><span>THERE IS A BETTER WAY.</span></div></div></article>
<div className="also"><div><span>05 / ALSO</span><h3>Menu bar only.</h3><p>No Dock icon. Egg is there without moving in.</p></div><div><span>↔</span><h3>Shake to open.</h3><p>Wiggle the cursor. The basket comes to you.</p></div><div><span>↗</span><h3>Hand it over.</h3><p>Anything in the basket can be given to an agent without leaving.</p></div></div></section>
<section className="cooking" id="still-cooking"><div className="cooking-heading"><span>A note from the person making this</span><h2>Still cooking.</h2></div><div className="cooking-copy"><p>A handful of us use Egg every day. It isn’t open yet; I’m letting people in slowly so I can keep up with what they tell me. Where things actually are:</p><p><strong>Search is its own app right now.</strong> It works, and it’s the best thing about Egg. Folding it into the feed is the next big job.</p><p><strong>The desktop side is being built.</strong> The feed is chronological and searchable today. That covers most of it. It isn’t finished.</p><p><strong>Apple only.</strong> macOS 14 or later, and an iPhone.</p></div></section>
<section className="bottom" id="early-access"><div className="window"><Bar title="KEEP IT."/><div className="bottom-body"><h2>Stop losing things<br/>you meant to keep.</h2><div className="access"><p>Would you like early access?</p><button disabled aria-describedby="signup-note">YES <span>↵</span></button></div><p className="signup-note" id="signup-note">Early-access signup is not open on this page yet.</p><p className="meta">macOS 14+ · iPhone · Made slowly</p></div></div></section>
</main></EggExperience>}
